In [3]:
import pandas as pd
import numpy as np

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [ ]:
id = np.arange(1, 11)
i2 = pd.Series(id)

gender = np.random.randint(2, size = 101)
g2 = pd.Series(gender)

age = np.random.randint(1,11, size = 101)
a2 = pd.Series(age)

region = np.random.randint(1,11, size = 101)
r2 = pd.Series(region)

df = pd.concat([i2, g2, a2, r2], axis = 1)
print(df.head())

#  출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
print(df.loc[0, 2])
print(df.loc[1, 3])
print(df.loc[4, 0])
print(df.loc[2, 0])
print(df.loc[3, 1])
df.loc[:, 0] = 10
print(df)

# null값을 3개 추가
df.loc[3,0] = np.nan
df.loc[3,2] = np.nan
df.loc[7,3] = np.nan
print(df.head(20))
print()


# null값의 개수를 확인하고 삭제
df_num = df.isnull().sum()
print(df_num)

df_drop = df.dropna()
print(df_drop)

# 2개의 데이터를 수정
df_drop.loc[0, 1] = '수정'
df_drop.iloc[0, 2] = '수정'
print(df_drop)

# 1개의 행을 삭제
df_drop.drop([0], axis = 0, inplace = True)
print(df_drop)

     0  1  2   3
0  1.0  0  4   4
1  2.0  1  4  10
2  3.0  1  4   5
3  4.0  1  4   5
4  5.0  0  8  10
4
10
5.0
3.0
1
        0  1  2   3
0    10.0  0  4   4
1    10.0  1  4  10
2    10.0  1  4   5
3    10.0  1  4   5
4    10.0  0  8  10
..    ... .. ..  ..
96   10.0  1  6   4
97   10.0  0  1   9
98   10.0  0  6   9
99   10.0  0  8   8
100  10.0  1  5   3

[101 rows x 4 columns]
       0  1     2     3
0   10.0  0   4.0   4.0
1   10.0  1   4.0  10.0
2   10.0  1   4.0   5.0
3    NaN  1   NaN   5.0
4   10.0  0   8.0  10.0
5   10.0  1   4.0   2.0
6   10.0  0   4.0   4.0
7   10.0  0   5.0   NaN
8   10.0  0   2.0   9.0
9   10.0  0   6.0   9.0
10  10.0  0   3.0   4.0
11  10.0  0   6.0  10.0
12  10.0  0  10.0   2.0
13  10.0  0   2.0   8.0
14  10.0  1   7.0   2.0
15  10.0  1   8.0   4.0
16  10.0  0   5.0   8.0
17  10.0  0   5.0   5.0
18  10.0  0   5.0   8.0
19  10.0  0   2.0   8.0

0    1
1    0
2    1
3    1
dtype: int64
        0  1    2     3
0    10.0  0  4.0   4.0
1    10.0  1  4.0  10.0
2    10.0  1  4.0   5.0
4    10.0  0  8.0  10.0
5    10.0  1  4.0   2.0
..    ... ..  ...   ...
96   10.0  1  6.0   4.0
97   10.0  0  1.0   9.0
98   10.0  0  6.0   9.0
99   10.0  0  8.0   8.0
100  10.0  1  5.0   3.0

[99 rows x 4 columns]
        0   1    2     3
0    10.0  수정   수정   4.0
1    10.0   1  4.0  10.0
2    10.0   1  4.0   5.0
4    10.0   0  8.0  10.0
5    10.0   1  4.0   2.0
..    ...  ..  ...   ...
96   10.0   1  6.0   4.0
97   10.0   0  1.0   9.0
98   10.0   0  6.0   9.0
99   10.0   0  8.0   8.0
100  10.0   1  5.0   3.0

[99 rows x 4 columns]
        0  1    2     3
1    10.0  1  4.0  10.0
2    10.0  1  4.0   5.0
4    10.0  0  8.0  10.0
5    10.0  1  4.0   2.0
6    10.0  0  4.0   4.0
..    ... ..  ...   ...
96   10.0  1  6.0   4.0
97   10.0  0  1.0   9.0
98   10.0  0  6.0   9.0
99   10.0  0  8.0   8.0
100  10.0  1  5.0   3.0

[98 rows x 4 columns]

<ipython-input-25-f7fc2f1f5681>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_drop.drop([0], axis = 0, inplace = True)

Task2_0527. 학생별 성적 데이터셋으로 의미있게 데이터 셋을 수정하세요.(아래 사항 반영)
- S1 ~ S10은 평균 점수를 기준으로 1등급에서 10등급이고 등급간 점수 차는 5점
- 결시자가 국어 3명, 수학 2명 있음
- 영어, 수학의 평균 점수가 국어 대비 5점 낮음

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(0)
df = np.random.randint(1,11, size=(10, 5))
df=pd.DataFrame(df,index=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'],
               columns=['국어','영어','수학','과학','사회'])

df.loc['s2', '국어'] = np.nan
df.loc['s3', '국어'] = np.nan
df.loc['s9', '국어'] = np.nan
df.loc['s3', '수학'] = np.nan
df.loc['s5', '수학'] = np.nan

df1 = df * 5

df1.mean()
df1

       국어  영어    수학  과학  사회
s1   30.0   5  20.0  20  40
s2    NaN  20  30.0  15  25
s3    NaN  35   NaN  45  10
s4   35.0  40  40.0  45  10
s5   30.0  50   NaN  50  25
s6   20.0   5  20.0  30   5
s7   15.0  20  45.0  10  20
s8   20.0  20  40.0   5  10
s9    NaN  50   5.0  25  40
s10  20.0  15  40.0  15   5

In [ ]:
# 등급간 점수 차는 5점
# df.iloc[0] # s1
# df.iloc[1] # s2

for i in range(10):
    df.iloc[i] = 90 - i * 5
df

In [ ]:
# 영어, 수학의 평균 점수가 국어 대비 5점 낮음
# df.iloc[0, 1:3] → 영어 85 / 수학 85
# df.iloc[0, 0] - 5 → 국어 90
for i in range(10):
    df.iloc[i, 1:3] = df.iloc[i, 0] - 5
df

In [ ]:
# 결시자가 국어 3명, 수학 2명 있음
a = df.copy()
a.iloc[7:, 0] = np.nan
a.iloc[8:, 2] = np.nan
a

Task3_0527. df1에서 결측값 처리 후 딕셔너리, 리스트로 변환하여 출력하세요.

In [8]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, np.nan, 88, 90, 76],
    "English": [92, 85, 89, np.nan, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, np.nan]
})
# 결측값 처리
# df1 = df1.fillna(0)
# df1

# 딕셔너리 및 리스트로 변환 시
# 먼저 해당 데이터프레임을 1-1. 배열로 바꾼 후 :
# df_value = df.values or df_arrays = df.to_numpy()
# 2. 리스트로 바꾼 후 : df_list = df_value.tolist()
# 1 - 2. 딕셔너리로 바꿀 수 있다. df_dict = df.to_dict('list')
df1_value = df1.values
print(df1_value, '\n')

df1_list = df1_value.tolist()
print(df1_list, '\n')

df1_dict = df1.to_dict('list')
print(df1_dict,'\n')

[['Alice' 85.0 92.0 78 88.0]
 ['Bob' nan 85.0 90 92.0]
 ['Charlie' 88.0 89.0 95 85.0]
 ['David' 90.0 nan 85 91.0]
 ['Eve' 76.0 80.0 89 nan]]

[['Alice', 85.0, 92.0, 78, 88.0], ['Bob', nan, 85.0, 90, 92.0], ['Charlie', 88.0, 89.0, 95, 85.0], ['David', 90.0, nan, 85, 91.0], ['Eve', 76.0, 80.0, 89, nan]]

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Math': [85.0, nan, 88.0, 90.0, 76.0], 'English': [92.0, 85.0, 89.0, nan, 80.0], 'Science': [78, 90, 95, 85, 89], 'History': [88.0, 92.0, 85.0, 91.0, nan]}

In [9]:
# Columns
df1.columns

Index(['Name', 'Math', 'English', 'Science', 'History'], dtype='object')

In [12]:
# 숫자 열에 대해 결측값을 각 열의 평균값으로 대체
df2 = df1.copy()
columns = ['Math', 'English', 'Science', 'History']
for column in columns:
    df2[column].fillna(df2[column].mean(), inplace = True)
df2

      Name   Math  English  Science  History
0    Alice  85.00     92.0       78     88.0
1      Bob  84.75     85.0       90     92.0
2  Charlie  88.00     89.0       95     85.0
3    David  90.00     86.5       85     91.0
4      Eve  76.00     80.0       89     89.0

In [13]:
df2_value = df2.values
print(df2_value, '\n')

df2_list = df2_value.tolist()
print(df2_list, '\n')

df2_dict = df2.to_dict('list')
print(df2_dict,'\n')

[['Alice' 85.0 92.0 78 88.0]
 ['Bob' 84.75 85.0 90 92.0]
 ['Charlie' 88.0 89.0 95 85.0]
 ['David' 90.0 86.5 85 91.0]
 ['Eve' 76.0 80.0 89 89.0]]

[['Alice', 85.0, 92.0, 78, 88.0], ['Bob', 84.75, 85.0, 90, 92.0], ['Charlie', 88.0, 89.0, 95, 85.0], ['David', 90.0, 86.5, 85, 91.0], ['Eve', 76.0, 80.0, 89, 89.0]]

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Math': [85.0, 84.75, 88.0, 90.0, 76.0], 'English': [92.0, 85.0, 89.0, 86.5, 80.0], 'Science': [78, 90, 95, 85, 89], 'History': [88.0, 92.0, 85.0, 91.0, 89.0]}

In [ ]:
# 배열로 변환
array1 = df2.to_numpy()
print(array1, '\n')

# 딕셔너리로 변환
dict1 = df2.to_dict(orient = 'list')
print(dict1, '\n')

# 리스트로 변환
list1 = df2.values.tolist()
print(list1, '\n')

Task4_0527. df2에서 아래와 같이 데이터 필터링 및 정렬 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.
- Math 점수가 80 이상인 학생만 선택
- English 점수를 기준으로 내림차순 정렬

In [ ]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, 79, 88, 90, 76],
    "English": [92, 85, 89, 93, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, 84]
})
df2_math = df2.loc[df2.Math >= 80,['Name', 'Math', 'English', 'Science', 'History']]

df2_math_englishsort = df2_math.sort_values(['English'])

# 데이터프레임(DF) → 배열(Value) 로 변경
df2_value = df2_math_englishsort.values
print(df2_value, '\n')

# 데이터프레임(DF) → 리스트(list) 로 변경
df2_list = df2_value.tolist()
print(df2_list, '\n')

# 데이터프레임(DF) → 딕셔너리(dict) 로 변경
df2_dict = df2_math_englishsort.to_dict('list')
print(df2_dict)

df2_math_englishsort

[['Charlie' 88 89 95 85]
 ['Alice' 85 92 78 88]
 ['David' 90 93 85 91]]

[['Charlie', 88, 89, 95, 85], ['Alice', 85, 92, 78, 88], ['David', 90, 93, 85, 91]]

{'Name': ['Charlie', 'Alice', 'David'], 'Math': [88, 85, 90], 'English': [89, 92, 93], 'Science': [95, 78, 85], 'History': [85, 88, 91]}

      Name  Math  English  Science  History
2  Charlie    88       89       95       85
0    Alice    85       92       78       88
3    David    90       93       85       91

Task5_0527. df3에서 각 학생의 평균 점수 계산 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.

In [14]:
df3 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice", "Bob", "Charlie", "David", "Eve"],
    "Subject": ["Math", "Math", "Math", "Math", "Math", "English", "English", "English", "English", "English"],
    "Score": [85, 79, 88, 90, 76, 92, 85, 89, 93, 80]
})

# df2_math = df2.loc[df2.Math >= 80,['Name', 'Math', 'English', 'Science', 'History']]
# data.groupby(['cluster'], as_index=False).mean()
df3_avg = df3.groupby('Name')['Score'].mean()

print(df3_avg)

df3_avg_value = df3_avg.values
print(df3_avg_value, '\n')

df3_avg_list = df3_avg_value.tolist()
print(df3_avg_list, '\n')

df3_avg_dict = df3_avg.to_dict()
print(df3_avg_dict, '\n')

Name
Alice      88.5
Bob        82.0
Charlie    88.5
David      91.5
Eve        78.0
Name: Score, dtype: float64
[88.5 82.  88.5 91.5 78. ]

[88.5, 82.0, 88.5, 91.5, 78.0]

{'Alice': 88.5, 'Bob': 82.0, 'Charlie': 88.5, 'David': 91.5, 'Eve': 78.0}

In [15]:
df3.pivot_table(index = 'Name', columns = 'Subject', values = 'Score', aggfunc = 'mean')

Subject  English  Math
Name
Alice         92    85
Bob           85    79
Charlie       89    88
David         93    90
Eve           80    76

In [16]:
df3_pivot = df3.pivot_table(index = 'Name', columns = 'Subject', values = 'Score', aggfunc = 'mean').reset_index()
df3_pivot.columns.name = None

print(df3_pivot)

      Name  English  Math
0    Alice       92    85
1      Bob       85    79
2  Charlie       89    88
3    David       93    90
4      Eve       80    76

Task6_0527. df4에서 특정 열의 데이터 타입을 변환한 후 변환된 타입을 확인하세요.

In [17]:
df4 = pd.DataFrame({
    'A': ['1', '2', '3', '4'],
    'B': ['5.1', '6.2', '7.3', '8.4'],
    'C': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01']
})

In [18]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      object
 1   B       4 non-null      object
 2   C       4 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes

In [21]:
# 'A'열을 정수형(int)으로 변환
df4['A'] = df4['A'].astype(int)

# 'B'열을 부동 소수점(float)으로 변환
df4['B'] = df4['B'].astype(float)

# 'C'열을 datetime으로 변환
df4['C'] = pd.to_datetime(df4['C'])

print(df4.dtypes)

A             int64
B           float64
C    datetime64[ns]
dtype: object

Task7_0527. df5에서 나이가 25 이상인 행을 출력하세요.

In [29]:
df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

# df2_math = df2.loc[df2.Math >= 80,['Name', 'Math', 'English', 'Science', 'History']]

df5_age = df5.loc[(df5.Age >= 25) & (df5.Name == 'Bob'), ['Name', 'Age', 'City']]
df5_age

  Name  Age         City
1  Bob   27  Los Angeles

In [27]:
subset = df5[df5['Age'] >= 25]
subset

    Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eve   29      Phoenix