In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

arr1 = np.array([10, 20, 30, 40, 50])<br>
arr2 = np.array([5, 15, 25, 10, 35])

In [7]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
print(arr1[arr2 > 10])

[20 30 50]

#### Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

In [6]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[ 5 15 25 35]

#### Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

arr = np.array([10, 25, 30, 15, 40, 5])

In [3]:
arr = np.array([10, 25, 30, 15, 40, 5])
arr[arr < 20] = 0
print(arr)

# or

np.where(arr < 20, 0, arr)
print(arr)

[ 0 25 30  0 40  0]
[ 0 25 30  0 40  0]