#### 파이썬 이란
- 1990년 암스테르담의 귀도 반 로섬(Guido Van Rossum)이 개발한 인터프리터 언어
- 컴퓨터 프로그래밍 교육을 위해 많이 사용하지만, 기업의 실무를 위해서도 많이 사용하는 언어. 구글에서 만든 소프트웨어의 50%이상이 파이썬으로 작성

#### 파이썬의 특징
- 파이썬은 인간다운 언어이다
- 파이썬은 문법이 쉬워 빠르게 배울 수 있다
- 파이썬은 무료이지만 강력하다
- 파이썬은 간결하다
- 파이썬은 프로그래밍을 즐기게 해준다
- 파이썬은 개발 속도가 빠르다

#### 파이썬으로 할 수 있는 일
- 웹 개발: Django, Flask 등의 프레임워크를 사용하여 웹 애플리케이션을 개발할 수 있습니다.
- 데이터 분석: Pandas, NumPy, SciPy와 같은 라이브러리를 사용하여 데이터를 분석하고 처리할 수 있습니다.
- 머신 러닝과 인공지능: TensorFlow, PyTorch, Scikit-learn 등의 라이브러리를 활용하여 머신 러닝 모델을 구축하고 훈련시킬 수 있습니다.
- 자동화: 파이썬 스크립트를 작성하여 일상적인 작업을 자동화하고, 시스템 관리 작업을 수행할 수 있습니다.
- 게임 개발: Pygame과 같은 라이브러리를 사용하여 간단한 게임을 개발할 수 있습니다.
- 모바일 애플리케이션 개발: Kivy 또는 BeeWare와 같은 라이브러리를 사용하여 모바일 애플리케이션을 개발할 수 있습니다.
- 데스크탑 애플리케이션 개발: PyQt, Tkinter 등의 라이브러리를 활용하여 데스크탑 애플리케이션을 개발할 수 있습니다.
- 시스템 스크립팅과 네트워킹: 시스템 유틸리티를 개발하거나 네트워크 프로토콜을 구현할 수 있습니다.
- 임베디드 시스템과 하드웨어 제어: 라즈베리 파이와 같은 임베디드 시스템을 제어하고 하드웨어를 프로그래밍할 수 있습니다.
- 사이언티픽 컴퓨팅: 과학적 연산과 시뮬레이션을 위해 파이썬을 활용할 수 있습니다.
- 교육: 파이썬은 초보자에게 프로그래밍을 가르치는 데 이상적인 언어로 평가받고 있습니다.
- 파이썬의 다양한 라이브러리와 프레임워크 덕분에, 이러한 분야에서의 작업이 더욱 쉽고 효율적으로 수행될 수 있습니다.

In [ ]:
# ! 기호는 Colab 셀에서 Unix/Liunx 셀 명령어를 실행
!python --version

Python 3.10.12

In [ ]:
# 라인 매직은 단일 라인에 대해 실행되며 % 하나를 사용하고 셀 매직은 셀 전체에 적용되며 %%를 사용
# 셀 전체에 적용시 %%를 사용함.
# 현재 작업폴더 확인
%pwd

'/content'

In [ ]:
%%time

sum = 0
for i in range(1000):
  sum+= i

print(sum)

499500
CPU times: user 245 µs, sys: 51 µs, total: 296 µs
Wall time: 302 µs

#### 용어
- 식별자 : 프로그램밍 언어에서 이름을 붙일 때 사용하는 단어. 주로 변수 또는 함수 이름 등으로 사용
- 주석 : 프로그램을 설명하기 위해 사용. # 기호로 주석 처리
- 연산자 : 스스로 값이 되는 것이 아니고 값과 값 사이에 무언가 기능을 적용할 때 사용
- 자료 : 리터럴이라고 하는데 숫자이든 문자이든 어떠한 값 자체를 의미. 1, 10, "Hello"
- 키워드 : 파이썬이 만들어질 때 이미 사용하겠다고 예약해 놓는 것. False, None, True, ...
- 프로그램밍 언어에서 사용자가 이름을 정할 때 키워드는 사용할 수 없음

#### 식별자
count, user_name, _is_valid, calculate_area, Car, model, year, math 및 m 모두 유효한 식별자. 각각의 식별자는 특정한 데이터 또는 기능에 이름을 부여하여 코드 내에서 해당 데이터나 기능을 참조할 수 있게하며 코드의 가독성과 유지 보수성을 높이는 데 중요한 역할

In [ ]:
# 변수 식별자
count = 10
user_name = 'Hyun'
_is_vaild = True

# 함수 식별자
def calculate_area(radius):
  return 3.141592 * radius * radius

# 클래스 식별자
class Car:
    def __init__(self, model, year):
        self.model = model
        self.year = year

# 모듈 식별자
import math as m

In [ ]:
calculate_area(3)

28.274328000000004

#### **식별자 기본 규칙**
- 키워드를 사용하면 안된다
- 특수문자는 언더 바만 사용
- 숫자로 시작하면 안된다.
- 공백을 포함할 수 없다.

In [ ]:
import keyword
print(keyword.kwlist, '\n')
len(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

35

In [ ]:
# Q. 주어진 문자열 리스트에서 유효한 Python 변수 이름만을 반환하는 함수를 작성하시오.
# result1 = text1.isalnum()
identifiers = ["var1", "2things", "variable_name", "time"]

def func1(x):
    return x.isalnum()

results = list(filter(func1, identifiers))
print(results)

['var1', '2things', 'time']

In [ ]:
identifiers = ["var1", "2things", "variable_name", "time!"]

import re

def check_integer_before_string(s):

    match = re.match(r'^(\d+)', s)
    # 문자열에 대해 정규식 패턴을 일치하려고함.
    # s. 패턴은 문자열( )의 시작 부분에 있는 r'^(\d+)'하나 이상의 숫자( )와 일치함.
    # 괄호는 일치하는 숫자를 캡처하는 캡처 그룹을 만드는 데 사용되며, 이 작업의 결과는 변수에 저장됨.

    if match:
      # 정규식 패턴과 일치하였는지 확인함.

        num_length = len(match.group(1))
        if len(s) > num_length and s[num_length].isalpha():
          # 1. 입력한 문자열의 길이가 s(num_length) 숫자의 길이보다 긴지 확인
          # 2. 숫자 바로 뒤의 문자 s가 알파벳 문자인지 확인
            return False
    return True
# 두 조건이 모두 True 이면 숫자 뒤에 문자가 있고 숫자 뒤에 첫 번째 문자가 문자라는 의미
# 19번 열에 있는 return False의 조건이 충족되면 함수는 False 입력한 문자열을 만족하지 않아 반환됨.
# 20번 열에 있는 return True 이전에 있는 조건 중 하나라도 충족되지 않거나 일치 항목이 하나도 없는 경우
# 이것들을 반환하여 True 입력하며, 문자열이 기준을 충족함을 나타냄
result = list(filter(check_integer_before_string, identifiers))
print(result)

result = check_integer_before_string("123abc")
print(result)  # False

result = check_integer_before_string("abc123")
print(result)  # true

['var1', 'variable_name', 'time!']
False
True

In [ ]:
# isidentifier()는 파이썬의 문자열 매서드로, 주어진 무자열이 유효한 식별자인지를 확인한다
# isidentifier()는 예약어인지는 따로 체크하지 않는다.

import keyword

def valid_identifiers(identifiers):
  valid = [] # 담을 그릇을 만듬
  for identifier in identifiers:
    if identifier.isidentifier() and not keyword.iskeyword(identifier):
      valid.append(identifier)
  return valid

print(valid_identifiers(identifiers))

['var1', 'variable_name']

#### **파이썬은 Snake_case와 CalmelCase를 모두 사용**
- itemlist:item_list / itemList
- loginstatus:login_status / loginStatus
- 캐멀 케이스(대문자로 시작) 클래스
- 스네이크 케이스(소문자로 시작) 뒤에 ()가 있다. → 함수
- 스네이크 케이스(소문자로 시작) 뒤에 ()가 없다. → 변수

In [ ]:
# 연산자

a = 5
b = 3
c = b % a
d = b // a
print(c)
print(d)

3
0

In [ ]:
a = 6
b = 5

if a > b:
  print(a)

6

#### **자료형**
- 자료형 또는 데이터 타입이란 숫자, 문자 등과 같이 여러 종류의 데이터를 구분하기 위한 분류
- 파이썬의 자료형은 크게 숫자(numbers), 시퀀스(sequence), 매핑(mapping) 등으로 나눌 수 있다.
- 파이썬의 기본 자료형
  - 수치형
    - 정수형 : int는 정수(integer)를 나타낸다. 양의 정수와 음의 정수, 숫자 0
    - 실수형 : float는 원래 부동소수점수(floating-point number)를 가리키는데, 지금은 단순히 소수점 이하를 표현할 수 있는 수이다.
    - 복소수형 : 복소수를 complex로 나타내고 제곱하면 -1이 되는 수 i를 ‘허수(imaginary number)’라고 하는데 허수 i를 j로 표현
  - 시퀀스 : 문자열(str), 리스트(list), 튜플(tuple), 사용자 정의 클래스가 시퀀스에 속한다. for 문에서 사용할 수 있는 것들이 바로 시퀀스
    - 문자열 : 문자를 한 줄로 표현하며 문자열 인덱스를 이용해 문자열의 일부를 복사
    - 리스트 : 대괄호([ ])로 감싸 주고 각 요솟값은 쉼표(,)로 구분
    - 튜플 : 튜플은 ( )으로 둘러싸고 각 요솟값은 쉼표(,)로 구분
  - 매핑
    - 사전 : 딕셔너리(dict)는 키(key)와 값(value)의 짝으로 이뤄지는데 이런 것을 매핑
  - 집합 : 집합을 표현하는 세트(set)
  - 블린 : 참, 거짓을 표현

In [ ]:
# 정수형, 실수형
i1 = 3
i2 = 3.5

print(i1, i2)

3 3.5

In [ ]:
# 정수(int)

print(int(True)) # True 인 경우 1로 나옴
print(int(False)) # False 인 경우 0으로 나옴
print(int('100'))
print(int(3.14))
# print(int('10a')) → Error(문자가 포함되어있기 때문에 오류 발생)

1
0
100
3

In [ ]:
# 실수(float)

print(float(True))
print(float(False))
print(float('3.141592'))
print(float(3.141592))

# print(float(3.141592a)) → 정수 때와 같은 이유로 오류 발생

1.0
0.0
3.141592
3.141592

In [ ]:
# 사칙연산 : +, *, /, //, %, **
a = 10
b = 2.3
print(a+b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

12.3
23.0
4.347826086956522
4.0
0.8000000000000007
199.52623149688787

In [ ]:
# 문자열
string = '문자열'
a = '100'

In [ ]:
print(string)
print(a)

문자열
100

In [ ]:
a1 = 101
print(a1)

101

In [ ]:
a = 100
b = 50
print(a+b)
a = '100'
b = '50'
print(a+b)
print(int(a)+int(b))

150
10050
150

In [ ]:
# 사용자 입력
input('인사말을 입력하세요 →')

인사말을 입력하세요 →0

'0'

In [ ]:
# input() 함수는 입력받은 데이터를 string으로 처리함

a = input()
b = input()

print(int(a)+int(b))

0
0
0

In [ ]:
# 두개의 정수를 입력해서 더한 결과를 출력하세요.

num1 = int(input('첫 번째 정수를 입력하세요 →'))
num2 = int(input('두 번째 정수를 입력하세요 →'))
print(num1+num2)

첫 번째 정수를 입력하세요 →0
두 번째 정수를 입력하세요 →0
0

In [ ]:
# 실수 + 실수 → 실수
# Q. 3과 3.3을 입력하고 숫자 연산을 수행하여 6.3을 출력하세요,

a = 3
b = 3.3
print(a+b)

6.3

In [ ]:
num3 = float(input('첫 번째 실수를 입력하세요 → '))
num4 = float(input('두 번째 실수를 입력하세요 → '))

print(num3+num4)

첫 번째 실수를 입력하세요 → 0
두 번째 실수를 입력하세요 → 0
0.0

In [ ]:
# Q. a = 52 와 b = 52.582 일 때 a+b는 5252.582 으로 출력되도록 a와 b를 문자열 자료형으로 변환하세요,
a = 52
b = 52.273
print(a+b)
a = str(a)
b = str(b)
print(a+b)

104.273
5252.273

In [ ]:
# 문자열 : "", '', """ """, ''' '''
# 백슬래시 (\)눈 문자열 안에서 작은따옴표(')를 문자열의 끝을 의미하지 않는 일반 문자로 포함시키기 위해 사용
# 이 기술을 이스케이프라고 함.

p1 = 'python\'s value is great'
print(p1)
p1 = "python's value is great"
print(p1)

python's value is great
python's value is great

In [ ]:
# \n : 행 바꿈 / \t : Tab의 효과
# y1 = "Once you study data anlysis You need Python"
y1 = "Once you study data anlysis \nYou need Python"
print(y1)
y1 = "Once you study data anlysis \t You need Python"
print(y1)

Once you study data anlysis
You need Python
Once you study data anlysis 	 You need Python

In [ ]:
y2 = """
Once you study data anlysis
'You need Python'
"""

print(y2)

Once you study data anlysis
'You need Python'

In [ ]:
a1 = 'python'
a2 = '\tis easy to learn'
print(a1+a2)
print("✌"*10)

python	is easy to learn
✌✌✌✌✌✌✌✌✌✌

In [ ]:
# Q. 아래와 같이 출력할 수 있는 string 을 만드세요.
# "What a wonderful world!"
# he said loudly

a1 ='''
" What a wonderful world!"
\the said loudly
'''
print(a1)
a1 = 'What a wonderful world!'
a2 = '\nhe said loudly'

print(str(a1), str(a2))

" What a wonderful world!"
	he said loudly

What a wonderful world!
he said loudly

In [ ]:
# Q. 다른 타입의 숫자 2개를 입력받아 큰 수를 출력하세요.

a = int(input('첫 번째 숫자를 입력하세요 →'))
b = int(input('두 번째 숫자를 입력하세요 →'))

if a > b:
    print(a)
elif a < b:
    print(b)
else:
    print('두 숫자가 같습니다.')

첫 번째 숫자를 입력하세요 →

ValueError: invalid literal for int() with base 10: ''

In [ ]:
# 자료형 - List
# 리스트는 []로 표시하며, []안의 요소를 콤마로 구분하여 순서있게 나열

list1 = [1,2,3,4,5]
list2 = ['a','b','c']
list3 = [1, 'a', 'abc', [1,2,3,4,5], ['a','b','c']]

print(list3)

In [ ]:
# 인덱싱

list1 = [1,2,3,4,5]
list2 = [1,3,5,8,9]
print(list1[3])
print(list1[0:4])
print(list1[:3])
print(list2[:3])
print(list2[0:])

In [ ]:
alist3 = [1, 'a', 'abc', [1,2,3,4,5], ['a','b','c']]

print(str(list3[4][1]))

In [ ]:
# 라스트 수정, 삭제

a = [1,2,3,4,5,6,7,8,9]
b = ['a', 'b', 'c']

del a[0]
a[-1] = 1

print(a)

del a[-1]
print(a)

In [ ]:
a = [1,2,3,4,5,6,7,8,9]
b = ['a', 'b', 'c']

print(a[-3])
print(a[-5:-2])
print(a[-6:])

In [ ]:
# 리스트 확장

a = [1,2,3]

# Extend : 반복 가능한 객체의 모든 요소를 리스트에 추가
a.extend([4,5,6])
a.extend([7])

print(a)

# append : 단일 객체를 추가한다.
a.append(10)

print(a)

# insert : 원하는 변수를 리스트 안에 넣는다. (넣고 싶은 인덱스 위치 , 넣고 싶은 변수)
a.insert(0,0)

print(a)

Q. list1에서 다음을 수행하세요
- 33을 출력
- 82를 리스트에 추가
- 87의 인덱스 구하기 - 도전
- 인덱스 3에서 10까지의 값을 출력하고 list2에 저장한 후 내림차순 정렬하기 - 도전
- 39를 11로 변경
- [69,45,58] 출력
- 짝수 인덱스의 값으로 구성된 리스트 출력하기
- 인덱스가 가장 큰수를 삭제하기
- 인덱스 3, 5인 값으로 4칙 연산하기

list1 = [58, 45, 69, 19,  4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]

In [ ]:
list1 = [58, 45, 69, 19,  4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]

# 33을 출력
print(list1[11][1],'\n')

# 82를 리스트에 추가
list1.append(82)
print(list1,'\n')

# 87의 인덱스 구하기
# for index, value in enumerate(list1):
#     print(f'Index: {index}, Value: {value}')
index = list1.index(87)
print(index,'\n')

# 인덱스 3에서 10까지의 값을 출력하고 list2에 저장한 후 내림차순 정렬하기 - 도전

list2 = list1[3:10]
print(list2)

# list2.sort(reverse=True)
sorted_list = sorted(list2, reverse=True) # 내림차순
sorted_list1 = sorted(list2) # 오름차순
print(sorted_list)
print(sorted_list1,'\n')

# 39를 11로 변경
list1[8] = 11
print(list1,'\n')

# [69,45,58] 출력
print([list1[2], list1[1], list1[0]],'\n')

# 짝수 인덱스의 값으로 구성된 리스트 출력하기
list3 = list1[::2]
print(list3,'\n')

# 인덱스가 가장 큰수를 삭제하기
del list1[-1]
print(list1,'\n')

# 인덱스 3, 5인 값으로 4칙 연산하기
print(list1[3] + list1[5])
print(list1[3] - list1[5])
print(list1[3] * list1[5])
print(list1[3] / list1[5])

In [ ]:
# :: 응용

print(list1)
print(list1[3::1])
print(list1[3::2])
print(list1[3::-1])
print(sorted(list1[3::-1]))

#### **sort 와 sorted 차이점**

1. 메서드 vs 함수:
- sort(): 리스트 객체의 내장 메서드입니다. 즉, 리스트에서만 사용할 수 있습니다.
- sorted(): 내장 함수로, 어떤 반복 가능한(iterable) 객체에도 사용될 수 있습니다. 예를 들면 리스트, 튜플, 딕셔너리, 문자열 등에 사용할 수 있습니다.

2. 반환 값:
- sort(): 리스트를 원 위치에서(in-place) 정렬하고 None을 반환합니다. 따라서 원래의 리스트 자체가 변경됩니다.
- sorted(): 정렬된 새로운 리스트를 반환합니다. 원래의 객체는 변경되지 않습니다.

3. 유용성:
- sort(): 리스트에서만 작동하기 때문에 리스트만 정렬할 수 있습니다.
- sorted(): 다양한 객체를 정렬할 수 있으며 결과는 항상 리스트로 반환됩니다.

In [ ]:
# sort()
my_list = [1, 3, 2]
my_list.sort()
print(my_list)

# sorted()
my_tuple = [3, 1, 2]
new_list = sorted(my_tuple)
print(my_tuple)
print(new_list)

In [ ]:
list = [1,2,3,4,5,1,2,3]

new_list = list.sort()
print(list)
print(new_list)

In [ ]:
list = [1,3,5,2,4]

new_list = sorted(list)
print(list)
print(new_list)

In [ ]:
my_list = [1, 2, 2, 3, 4, 4, 5]
unique_list = list(set(my_list))
print(unique_list)

In [ ]:
list1 = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63 ,98 ,22 ,82]
print(list1[11])
print(list1[3:10])
list2 = list1[3:11]
l_sort = sorted(list2,reverse=True)
print(l_sort)

In [ ]:
list3 = list1[3:11]
list3.sort(reverse=True)
print(list3)

## **Task1_0425. 주어진 숫자 리스트에서 최소값과 최대값을 찾아 출력하세요.**

numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

In [ ]:
# index = list1.index(87)

numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

sort_numbers = sorted(numbers,reverse=True)

Max = sort_numbers[0]
Min = sort_numbers[-1]

print(f"최댓값 : {Max}, 최솟값 : {Min} ")

최댓값 : 87, 최솟값 : 4

In [ ]:
# 2번째 풀이

# 최솟값과 최대값을 첫 번째 요소로 초기화합니다.
Min_value = numbers[0]
Max_value = numbers[0]

for i in numbers:
  if Max_value < i:
    Max_value = i
  elif Min_value > i:
    Min_value = i

print(f"최댓값 : {Max_value}, 최솟값 : {Min_value} ")

최댓값 : 87, 최솟값 : 4

## **Task2_0425. 주어진 숫자 리스트의 모든 요소의 합계와 평균을 계산하고 출력하세요**

numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

In [ ]:
numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

Add = numbers[0]+numbers[1]+numbers[2]+numbers[3]+numbers[4]+numbers[5]+numbers[6]+numbers[7]+numbers[8]+numbers[9]
print(Add)

ag = ((numbers[0]+numbers[1]+numbers[2]+numbers[3]+numbers[4]+numbers[5]+numbers[6]+numbers[7]+numbers[8]+numbers[9])/10)
print(ag)

# 합계 계산
total = sum(numbers)

# 평균 계산
average = total / len(numbers)

# 결과 출력
print(f"합계 : {total}, 평균 : {average}")

In [ ]:
import numpy as np

print(f" 합계 : {sum(numbers)}, 평균 : {np.mean(numbers)}")

In [ ]:
import statistics

average = statistics.mean(numbers)
print(f'평균 : {average}')

## **Task3_0425. 주어진 리스트에서 특정 요소가 등장하는 모든 인덱스를 리스트로 만들어 출력하세요.**

items = ['apple', 'banana', 'cherry', 'apple', 'cherry', 'apple']

target = 'apple'

In [ ]:
items = ['apple', 'banana', 'cherry', 'apple', 'cherry', 'apple']

sort_items = sorted(items)
print(sort_items[0:3])

# 다른 풀이

target = 'apple'

indexes = [index for index, value in enumerate(items) if value == target]

print(f"'{target}'의 모든 인덱스 : {indexes}")

## **Task4_0425. 주어진 리스트에서 연속해서 반복되는 요소만 제거하고, 결과 리스트를 반환하세요. 단, 처음 등장하는 요소는 유지해야 합니다.**

예를 들어, ['a', 'a', 'b', 'c', 'c', 'c', 'd', 'e', 'e']가 입력되면, ['a', 'b', 'c', 'd', 'e']를 출력해야 합니다.

In [ ]:
list1 = ['a','a','b','c','c','c','d','e','e']
set_list = sorted(set(list1))
print(set_list)

In [ ]:
result = [list1[0]]

for i in list1[1:]:
  if i != result[-1]:
    result.append(i)

print(result)

In [ ]:
def remove_consecutive_duplicates(list1):
    result = [list1[0]] # 이게 없으면 전에 있는 결과랑 중첩해서 나옴
    for i in list1[1:]:
      if i != result[-1]:
        result.append(i) # 여기까지 전이랑 동일함
    return result

print(remove_consecutive_duplicates(list1))

## **Task5_0425 주어진 정수 리스트와 회전 횟수 k에 대해 리스트를 오른쪽으로 k만큼 회전시킨 결과를 반환하세요. k가 리스트의 길이보다 클 수 있으며, 이 경우 k를 리스트 길이로 나눈 나머지만큼 실제 회전시키면 됩니다.**

예를 들어, [1, 2, 3, 4, 5]와 k=2가 주어지면, 결과는 [4, 5, 1, 2, 3]이 되어야 합니다.

In [ ]:
list1 = [1, 2, 3, 4, 5]
k = 10

def right_rotate(list1, k):
  k = k % len(list1)
  return list1[-k:] + list1[:-k]

print(right_rotate(list1,k))
print(right_rotate(list1,1)) # [5, 1, 2, 3, 4]
print(right_rotate(list1,2)) # [4, 5, 1, 2, 3]
print(right_rotate(list1,4))
print(right_rotate(list1,7))

# 주어진 리스트 list1의 마지막 k개의 요소를 리스트의 처음으로 이동시키는 것을 의미합니다.

# 여기서 list1[-k:]는 리스트의 마지막 k개의 요소를 나타내며,
# list1[:-k]는 리스트의 처음부터 마지막에서 k번째 요소까지를 나타냅니다.
# 따라서 list1[-k:] + list1[:-k]는 마지막 k개의 요소가 리스트의 앞에 오고, 그 앞에는 처음부터 마지막에서 k번째 요소까지의 요소가 오는 새로운 리스트를 만듭니다.

# 예를 들어, list1이 [1, 2, 3, 4, 5]이고 k가 2라면, list1[-2:]는 [4, 5]이고 list1[:-2]는 [1, 2, 3]입니다. 따라서 list1[-2:] + list1[:-2]는 [4, 5, 1, 2, 3]이 됩니다.

In [ ]:
# 왼쪽으로 가는 버전

list1 = [1, 2, 3, 4, 5]
k = 10

def left_rotate(list1, k):
  k = k % len(list1)
  return list1[k:] + list1[:k]

print(left_rotate(list1,2))

### **자료형 - Tuple**

- 튜플은 변경할 수 없는(immutable) 순서가 있는 컬렉션
- 프로그램에서 그 값이 항상 변하지 않아야되는 경우 사용

In [ ]:
tuple1 = (1,2,3,4,5)
tuple2 = ('a', 'b', 'c')
tuple3 = (1, 'a', 'abc', [1,2,3,4,5], ['a', 'b', 'c'])

print(tuple1[:])
print(tuple2[2])
tuple3[3][2]

In [ ]:
# , 가 없는 경우 int로 나옴
# , 가 있는 경우 Tuple 의 형태임.
t1 = (1,)

print(t1)
type(t1)

In [ ]:
# 소괄호가 없어도 튜플로 표현 가능

t2 = 1,2,3

print(t2)
type(t2)

In [ ]:
# List 끼리 합연산 가능
[1,2,3]+[4,5,6]

In [ ]:
print(list1*4)
print(t2*4)

In [ ]:
t1+t2

### Q. 'red', 'green', 'blue' 값을 갖는 튜플에서 각 값을 각각 r,g,b 변수에 할당하고 출력하세요.

In [ ]:
colors = ('red', 'green', 'blue')
r,g,b = colors

print(r)
print(g)
print(b)

a,b,c = colors

print(a)
print(b)
print(c)

### 함수에서 여러 값을 반환할 때 튜플을 사용하는 것이 일반적입니다.
### Q. 주어진 리스트의 총합과 평균을 동시에 반환하는 함수를 작성하세요.
### numbers = [10,20,30,40,50]

In [ ]:
numbers = [10,20,30,40,50]

def calculate_sum_and_average(numbers):
  total = sum(numbers)
  average = total / len(numbers)
  return (total, average)

total, average = calculate_sum_and_average(numbers)
print(f'총합은 {total}, 평균은 {average} 입니다.')

## 자료형 - 사전
- 키와 값을 하나의 요소로 하는 순서가 없는 집합

In [ ]:
d1 = {'a':1, 'b':2, 'c':3}
print(d1['a'])

In [ ]:
d1.keys()

In [ ]:
d1.values()

In [ ]:
d1.items()

In [ ]:
d1['d']=4
d1

In [ ]:
d1['딕셔너리'] = 5
d1

In [ ]:
d1['딕셔너리'] = 6
d1

In [ ]:
del d1['딕셔너리']
d1

In [ ]:
d1['b'] = 7
d1

In [ ]:
del d1['b']
d1

### Q. 딕셔너리 d에서 'b'의 값을 확인하면서 그 값을 삭제하세요

In [ ]:
d = {'a':1, 'b':2, 'c':3, 'd':4}
value = d.pop('b')
print("삭제 값 : ", value)
print(d)

### Q. 다음과 같이 학생의 이름과 점수를 튜플로 묶은 리스트가 있습니다. [("Tom",85), ("Jane",90), ("Bob",75)] 이 리스트를 사용해 학생 이름을 키로, 점수를 값으로 하는 딕셔너리를 생성하고 출력하세요

### Q. 튜플의 불변성 때문에 튜플은 딕셔너리의 키로 사용될 수 있습니다. 주어진 위치 좌표 리스트에서 각 위치가 몇 번 나타나는지 계산하는 딕셔너리를 만드세요.
### positions = [(1,1), (2,2), (1,1), (3,3), (2,2)]

In [ ]:
list1 = [("Tom",85), ("Jane",90), ("Bob",75)]

tuple1 = list1[0], list1[1], list1[2]
a,b,c = tuple1

a1, a2 = a
b1, b2 = b
c1, c2 = c

tuple2 = a1, b1, c1
tuple3 = a2, b2, c2

list2 = list(tuple2)
list3 = list(tuple3)

list2[0] = '174cm'
list2[1] = '164cm'
list2[2] = '184cm'

dict_list= dict(zip(list2,list3))
print(dict_list)

# 다른 풀이

{'174cm': 85, '164cm': 90, '184cm': 75}

In [ ]:
positions = [(1,1), (2,2), (1,1), (3,3), (2,2)]

positions_count = {}
for i in positions:
  if i in position_count
    positions

## 자료형 - 집합, set
- 중복을 허용하지 않으며 순서가 없다.

In [ ]:
s1 = set([1,2,3,4,5])
s2 = set('Hello')

print(s1)
print(s2)

In [ ]:
list1 = list(s1)

print(list1)
print(list1[2])

In [ ]:
list2 = list(s2)
print(list2)
print(list2[2])

### Q. 주어진 리스트에서 중복 요소를 제거하고 결과를 출력하세요. nums = [1,2,2,2,3,4,4,4,5]

In [ ]:
nums = [1,2,2,2,3,4,4,4,5]

set1 = set(nums)
set2 = list(set1)
print(set2)

### Q. s1, s2의 합집합과 교집합을 각각 리스트로 출력하세요.

In [ ]:
s1 = set([1,2,3,4,5,6])
s2 = set([4,5,6,7,8,9])

union_1 = s1.union(s2) # or s1 | s2
union1 = list(union_1)
print(f'합집합은 {union1} 입니다.')

inter_1 = s1.intersection(s2) # s1 & s2
inter1 = list(inter_1)
print(f'교집합은 {inter1} 입니다.')

### Q. 첫 번째 집합에서 두 번째 집합의 요소를 제외한 차집합을 구하고 출력하세요.

In [ ]:
set1 = {1,2,3,4,5}
set2 = {4,5,6,7}

set3 = set1 - set2
print(f'차집합은 {list(set3)} 입니다.')

### Task1_0426. 주어진 리스트에서 중복된 요소를 제외하고 고유한 요소의 개수를 세는 프로그램을 작성하세요.

data = [1, 2, 2, 3, 4, 4, 4, 5]

In [ ]:
data = [1, 2, 2, 3, 4, 4, 4, 5]

set1 = set(data)

print(len(list(set1)))

5

### Task2_0426. 두 개의 리스트에서 공통으로 나타나는 요소들을 찾아 리스트로 반환하는 프로그램을 작성하세요.

예시 입력: list1 = [1, 2, 3, 4, 5], list2 = [4, 5, 6, 7, 8]

예시 출력: [4, 5]

In [ ]:
# 과제

list1 = set([1, 2, 3, 4, 5]); list2 = set([4, 5, 6, 7, 8])

subt1 = list1.intersection(list2)
print(list(subt1))

[4, 5]

## 자료형 - 논리(Bool) True와 False
- 파이썬에서 참과 거짓을 나타내는 상수, True는 1, False는 0의 값을 가짐
- 조건을 판단해서 그 조건이 참이면 True, 거짓이면 False를 return한다.

In [ ]:
# 자료형 - 논리(Bool)
print(bool(0))
print(bool(''))
print(bool([]))
print(bool(1))
print(bool(100))

False
False
False
True
True

```
아스키코드
ASCII 값에서 'a'는 97이고 'p'는 112입니다.
'a'는 'p'보다 작으므로 str1 < str2 는 True로 반환된다.
```

In [ ]:
# 관계 연산자
x = 1; y = 2
str1 = 'abc'; str2 = 'python'
print(x == y)
print(x != y)
print(str1 == str2)
print(str2 == 'python')+

print(str1 < str2)
print(x == str1) # int 와 str 은 같은지 다른지에 대해서 T/F 판단 여부 가능 크기 관련은 같은 종류의 인덱스만 판단 가능

In [ ]:
# 논리 연산자
bool1 = True; bool2 = False; bool3 = True; bool4 = False

print(bool1 and bool2)
print(bool1 or bool2)
print(not bool3)
print(not (bool4 and bool3))

### Task3_0426. 주어진 숫자 리스트에서 특정 값보다 큰 요소가 하나라도 존재하는지 검사하고, 그 결과를 불 값으로 반환하는 함수를 작성하세요.

- numbers = [1, 2, 3, 10, 20]
- threshold = 15

### Task4_0426. 주어진 문자열이 특정 문자열을 포함하는지 확인하고 결과를 불 값으로 반환하는 함수를 작성하세요.

- text = "hello world"
- substring = "world"

### Task5_0426. 주어진 연도가 윤년인지 판별하는 함수를 작성하세요. 윤년은 다음의 조건을 만족해야 합니다:
- 4로 나누어 떨어진다.
- 100으로 나누어 떨어지지 않거나, 400으로 나누어 떨어지면 윤년이다.

year = 2020

True

In [ ]:
year = 2020

if year // 4 == 0:
    print(f'{year}년은 윤년입니다.')
elif year // 100 != 0:
    print(f'{year}년은 윤년이 아닙니다.')
elif year // 400 == 0:
    print(f'{year}년은 윤년입니다.')
else:
    print(f'{year}년은 윤년이 아닙니다.')

2020년은 윤년이 아닙니다.

#### 파이썬에서 들여쓰기
- 파이썬에는 실행 코드 부분을 묶어주는 {} 괄호가 없다.
- 대신 들여쓰기(indentation)로 {}를 대신한다.
- 제어문이나 함수이름, 클래스 이름 뒤에 콜론(':')으로 제어문, 함수이름, 클래스 이름의 끝을 표시하며 ':' 다음에 실행 코드를 작성

In [ ]:
li = ['a', 'b', 'c']
if 'a' in li:
  print('a가 li에 있습니다.')
else:
  print('a가 li에 없습니다.')

In [ ]:
numbers = [1,2,3]
sum(numbers)

# 사용자 함수
def add(a,b,c):
  return a+b+c

add(1,2,3)

### Q. 뺄셈, 나눗셈을 수행하는 사용자 함수를 작성하세요.

In [ ]:
def subt(a,b,c):
  return a-b-c

subt(10,1,1)

In [ ]:
def div(a,b,c):
  if b == 0 or c == 0:
    return 'Error : Division by Zero'
  else:
    return a/b/c

div(10,1,1)

### 클래스

In [ ]:
class AddMul:
  def add(self,n1,n2):
    return n1 + n2
  def mul(self,n1,n2):
    return n1 * n2

obj1 = AddMul()
print(obj1.add(1,1))
obj2 = AddMul()
print(obj2.mul(3,2))

2
6

### Task6_0426. Calculator 클래스를 작성하고 4칙연산을 수행하는 객체 4개를 작성하여 결과를 출력하세요.

# Task7_0426. 다음 과제를 수행하세요.
- 사용자로 부터 텍스트를 입력 받는다.
- 문자을 단어 단위로 분리 : split()
- 단어의 빈도수를 저장할 딕셔너리를 생성
- 각 단어의 빈도 수를 계산(for 문 / if else문):word =word.lower()
- 결과 출력

[ 예시 ]

문장을 입력하세요: I love apple. I love orange. Apple is tasty

{'i': 2, 'love': 2, 'Apple.': 1, 'orange.': 1, 'apple': 1, 'is': 1, 'tasty': 1}

In [1]:
# split() 함수

text = '나는 오늘 매우 기분이 좋아요'
words = text.split()
words

['나는', '오늘', '매우', '기분이', '좋아요']

In [3]:
text = 'apple, banana, orange'
words = text.split(',')
words

['apple', ' banana', ' orange']

In [4]:
time_string = '10:47:05'
time_list = time_string.split()
time_list

['10:47:05']

In [9]:
# Q. multi_line_text를 아래 리스트로 분리해 보세요.
multi_line_text = "Hello\nWorld\nPython\nProgramming"
# print(multi_line_text)

lines = multi_line_text.split('\n')
lines

['Hello', 'World', 'Python', 'Programming']

In [10]:
# 복합 대입 연산자
num = 10
num += 10 # num = num + 10
num

20

In [22]:
# Q. 복합 대입연산자를 이용해서 4칙연산을 수행하세요

a = 10
a += 5
print('덧셈 후:', a )
a -= 5
print('뺄셈 후:', a)
a *= 3
print('곱셈 후:', a)
a /= 3
print('나눗셈 후:', a)
a

덧셈 후: 15
뺄셈 후: 10
곱셈 후: 30
나눗셈 후: 10.0

10.0

In [23]:
# 소문자, 대문자 변환

word = 'Dog'
word_lower = word.lower()
print(word_lower)
word_upper = word.upper()
print(word_upper)

dog
DOG

### Task1_0429.

input_str = "Hello, world! How are you today? l am fine. Thank you!"

['Hello', 'world', 'How', 'are, 'you', 'today', 'I', 'am'. 'fine', 'Thank', 'you', '']

## 이스케이프 문자

- 키보드로 입력하기 어려운 기호 등을 나타낸다.
- 역 슬레시로 시작, ＼n

In [29]:
print("Hello\tWorld!")
print("Hello\nworld!")
print("She said, \"HI!\:")
print("it\'s, raining")
print("Backslash: \\")

Hello	World!
Hello
world!
She said, "HI!\:
it's, raining
Backslash: \

#### 문자열 포멧
- % operator 사용 : % 연산자를 사용하려면 %(VAR_NAME)TYPE 형식으로 적어주며 VAR_NAME 은 바인딩할 변수명을 TYPE 은 변수의 유형을 적어준다.
- str.format : str.format() 은 파이썬 표현식 값을 바인딩할 부분을 중괄호 {} 로 표시하고 .format() 뒤에 바인딩할 값을 기술해 준다.
- f-string : 문자열에 f 나 F 접두사를 붙이고 표현식을 {expr} 형식으로 작성하면 출력 문자열이 파이썬 표현식의 값으로 바뀐다.

In [37]:
text1 = '자바'; text2 = '파이썬'
num1 = 5; num2 = 10
print('나는 %s보다 %s에 더 익숙합니다.' %(text1, text2))
print('%s은 %s보다 %d배 더 쉽습니다.' %(text2, text1, num1))
print('%d + %d = %d' %(num1, num2, num1+num2))
print('작년 세계 경제 성장률은 전년에 비해 %d%% 포인트 증가했다.' %(num1))

나는 자바보다 파이썬에 더 익숙합니다.
파이썬은 자바보다 5배 더 쉽습니다.
5 + 10 = 15
작년 세계 경제 성장률은 전년에 비해 5% 포인트 증가했다.

In [40]:
# str.format
print('We are the {} who say "{}"'.format('knights', 'Ni'))

We are the knights who say "Ni"

In [41]:
# f-string
name = '홍길동'
age = 30

f'나의 이름은 {name}, 나이는 {age}입니다.'

'나의 이름은 홍길동, 나이는 30입니다.'

In [43]:
table = {'Tom':1234, 'Jack':4518, 'Eddie':9638}
for name, phone in table.items():
    print(f'{name:5} → {phone:4d}')

Tom   → 1234
Jack  → 4518
Eddie → 9638

In [44]:
# 소수점 4자리까지만 표현
y = 3.141592
f'{y:0.2f}'

'3.14'

In [47]:
# 소수점 4자리까지 표현하고 총 자리수를 10으로 맞춤
y = 3.141592
f'{y:7.4f}'

' 3.1416'

In [59]:
# Q. num1 = 12345, num2 = 12.345679 을 아래와 같이 출력하세요.
# 12345
#      12345
# 12.345679
#           12.346

num1 = 12345; num2 = 12.345679
print(f'{num1}')
print(f'{num1:10}')
print(f'{num2}')
print(f'{num2:15.3f}')

12345
     12345
12.345679
         12.346

#### 2진수, 8진수, 16진수의 데이터 표현 방법

- 우리가 프로그래밍을 하면서 변수에 어떤 값을 저장할 때 10진수는 일상적 표현을 그대로 대입한다.
- 예를들어 15를 저장하고 싶다면 int a= 15; 와 같이 15라는 숫자를 그대로 대입하면 된다.
- 하지만 2진수, 8진수, 16진수는 표현법이 따로 정해져있다.<br><br>  

- 2진수는 대입하고자 하는 값 앞에 0b를 붙인다. (숫자0과 영문자b)
- 8진수는 대입하고자 하는 값 앞에 0o 을 붙인다. (숫자0 영문자o)
- 16진수는 대입하고자 하는 값 앞에 0x 를 붙인다. (숫자0과 영문자x)

아래의 예시를 보자.
변수 a,b,c,d 는 모두 10진수 122 이라는 값을 저장하는 코드이다.

122는
- 2진수로 1111010
- 8진수로 172
- 16진수로 7A 이다.

In [60]:
a = 0o172
b = 0x7A
c = 0b1111010
print(a)
print(b)
print(c)

122
122
122

In [62]:
# Q. 10을 10진수, 2진수, 8진수, 16진수로 출력하세요

a = 10
b = 0b1010
c = 0o12
d = 0xA

print(a)
print(b)
print(c)
print(d)

10
10
10
10

In [64]:
# 2진수를 10진수로 표현
g1 = 0b1000
g2 = 0b100
g3 = 0b10
g4 = 0b1

print(g1)
print(g2)
print(g3)
print(g4)

8
4
2
1

In [65]:
# 16진수를 10진수로 표현
f1 = 0xA
f2 = 0xAB
f3 = 0xABC
f4 = 0xABCD

print(f1)
print(f2)
print(f3)
print(f4)

10
171
2748
43981

In [67]:
# Q. 0xABC를 계산하세요.

print(0xABC)
print(16**2*10+16**1*11+12)

2748
2748

### Task2_0429. 십진수 122를 2진수, 8진수, 16진수로 변경하여 출력하세요.

In [74]:
print(f'2진수로 표현 : {0b1111010}')
print(f'8진수로 표현 : {0o172}')
print(f'16진수로 표현 : {0x7A}')

2진수로 표현 : 122
8진수로 표현 : 122
16진수로 표현 : 122

### Task3_0429. 두 수의 곱셈 결과를 계산하고, 그 결과에 10을 더하세요.

In [84]:
num1 = 10; num2 = 5

print(f'{num1} * {num2} = {num1*num2}')
print(f'%d * %d + 10 = %d' %(num1, num2, num1*num2+10))

10 * 5 = 50
10 * 5 + 10 = 60

Task4_0429. 주어진 리스트에서 두 번째 요소를 삭제하고, 마지막에 새로운 요소 'Python'을 추가하세요.

리스트: ['Java', 'C', 'JavaScript']

In [93]:
list1 = ['Java', 'C', 'JavaScript']

del list1[1]

list1.append('Python')

print(list1)

['Java', 'JavaScript', 'Python']

### Task5_0429. 주어진 문자열에서 처음 세 글자와 마지막 세 글자를 연결하여 새로운 문자열을 만드세요.

문자열: 'Incredible'

In [6]:
word = 'Incredible'

word = list((sorted(word[0:3])) + sorted(word[-3:]))

word_list = list(word)

word_list[1], word_list[2] = word_list[2], word_list[1]
word_list[4], word_list[5] = word_list[5], word_list[4]

print(''.join(word_list))

Incble

### Task6_0429. 사용자의 이름과 이메일을 딕셔너리로 저장하고, 이름을 입력받아 해당하는 이메일을 출력하세요.

사용자 정보: 이름 - 'Alice', 이메일 - 'alice@example.com'

In [93]:
User_Name_Public = 'Alice'
User_Email_Alice = 'alice@example.com'

User_dic = {}

User_dic['Alice'] = 'alice@example.com'

print(User_dic)

User_Name = str(input('이름을 입력하세요 : '))

if 'Alice' in User_Name:
  print(f'{User_Email_Alice}')
else:
  print(f"등록되어있는 정보가 없네요")

{'Alice': 'alice@example.com'}
이름을 입력하세요 : Alice
alice@example.com

### Task7_0429. 주어진 두 튜플에서 공통 요소만을 찾아 집합으로 만드세요.

튜플: (1, 2, 3, 4, 5)와 (4, 5, 6, 7, 8)

In [26]:
Tuple_1 = (1,2,3,4,5)
Tuple_2 = (4,5,6,7,8)

list_1 = set(list(Tuple_1))
list_2 = set(list(Tuple_2))


list_3 = list_1.intersection(list_2)
print(list_3)

{4, 5}

### Task8_Challenge_0429. 다음 요구 사항을 충족하는 프로그램을 작성하세요:

- 사용자로부터 이름, 나이, 좋아하는 색상을 입력받습니다.
- 입력받은 정보를 딕셔너리로 저장하고, 모든 사용자 정보를 리스트에 저장합니다.
- 이름이 'John'인 사용자의 정보만 출력하세요.
- 전체 사용자의 평균 나이를 계산하고 출력하세요.

1. 사용자 데이터:
- 이름: John
- 나이: 28
- 좋아하는 색상: Blue
2. 사용자 데이터:
- 이름: Alice
- 나이: 24
- 좋아하는 색상: Red
3. 사용자 데이터:
- 이름: Maria
- 나이: 32
- 좋아하는 색상: Green

In [61]:
User_name_1, User_age_1, User_like_color_1 = input('이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> ').split(' ')
User_name_2, User_age_2, User_like_color_2 = input('이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> ').split(' ')
User_name_3, User_age_3, User_like_color_3 = input('이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> ').split(' ')

print('\n')

User_list = []
User_information = {"이름": name, "나이": age, "좋아하는 색깔": color}
User_list.append(User_information)

for i in range(3):
  name, age, like_color = input

User_dic[User_name_1] = User_age_1, User_like_color_1
User_dic[User_name_2] = User_age_2, User_like_color_2
User_dic[User_name_3] = User_age_3, User_like_color_3

print(User_dic)
print('\n')

if 'John' in User_dic.keys():
    print(f'{User_name_1}님의 나이는 {User_age_1}살이며, 좋아하는 색상은 {User_like_color_1} 입니다.')

print('\n')
print(((int(User_age_1) + int(User_age_2) + int(User_age_3)) / 3))

이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> John 28 Blue
이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> Alice 24 Red
이름, 나이, 좋아하는 색상을 스페이스 바를 기준으로 나눠서 입력하세요 >> Maria 32 Green


{'John': ('28', 'Blue'), 'Alice': ('24', 'Red'), 'Maria': ('32', 'Green')}


('28', 'Blue')
John님의 나이는 28살이며, 좋아하는 색상은 Blue 입니다.


28.0

In [92]:
users = []

# 사용자 정보 입력 및 저장
for i in range(3):
    name = input("이름: ");age = int(input("나이: "));color = input("좋아하는 색깔: ")
    user_infomation = {"이름": name, "나이": age, "좋아하는 색깔": color}
    users.append(user_infomation)

print('\t')
print(users)
print('\t')

# 이름이 'John'인 사용자의 정보 출력
print("이름이 'John'인 사용자의 정보:")

for i in users:
    if i["이름"] == 'John':
        print("이름:", i["이름"])
        print("나이:", i["나이"])
        print("좋아하는 색깔:", i["좋아하는 색깔"])
        break
    else:
        print("이름이 'John'인 사용자를 찾을 수 없습니다.")

# 전체 사용자의 평균 나이 계산
total_age = sum(i["나이"] for i in users)
average_age = total_age / len(users)

print('\n')
print(f'사용자들의 전체 나이 평균은 : {average_age} 입니다.')

이름: John
나이: 28
좋아하는 색깔: Blue
이름: Alice
나이: 24
좋아하는 색깔: Red
이름: Maria
나이: 32
좋아하는 색깔: Green

[{'이름': 'John', '나이': 28, '좋아하는 색깔': 'Blue'}, {'이름': 'Alice', '나이': 24, '좋아하는 색깔': 'Red'}, {'이름': 'Maria', '나이': 32, '좋아하는 색깔': 'Green'}]

이름이 'John'인 사용자의 정보:
이름: John
나이: 28
좋아하는 색깔: Blue


사용자들의 전체 나이 평균은 : 28.0 입니다.